"""empty message

Revision ID: eab41b4c76f8
Revises: 939e6cee09bf
Create Date: 2022-05-25 14:19:15.269781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab41b4c76f8'
down_revision = '939e6cee09bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'animal', ['species'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'animal', type_='unique')
    # ### end Alembic commands ###
